import { clsxMerge } from '@/src/utils/clsxMerge';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { useAppContext } from '../../app/AppContextProvider';
import { Header } from './Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const Layout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  const { isDarkTheme } = useAppContext();
  return (
    <div
      className={clsxMerge('flex flex-col', 'w-full', isDarkTheme && 'dark')}
    >
      <Header />
      <main className="max-w-7xl lg:px-8">{children}</main>
      <footer>This is the footer</footer>
    </div>
  );
};
