import { clsxMerge } from '@/src/utils/clsxMerge';
import type { Metadata } from 'next';
import { useState } from 'react';
import { Header } from './Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const [isDark, setIsDark] = useState(true);
  return (
    <div className={clsxMerge('flex flex-col gap-4', isDark && 'dark')}>
      <Header setIsDark={setIsDark} />
      <section>{children}</section>
      <footer>This is the footer</footer>
    </div>
  );
};
